### ISSUE TITLE
Make schema type override of SIMON a parameter

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-ingest#116]
For the WM Dec. demo we're using SIMON values as the types applied on ingest rather than the schema types.  This is necessary because we import from CSV on the fly, and the default type of text needs to be overidden.   This will also result in the schema type being ignored on ingest from a standard D3M dataset.  We should make this a parameter than can be toggled based on use case.

**Comment by phorne-uncharted** [comment]
Since everything now defaults to unknown type, I updated the probability from schema to be 1.0 unless the type is unknown (in which case it stays 0). There is already a mechanism in place to bias the complex SIMON so that they can surface more effectively.
